---
  - name: Provision an EC2 Instance
    hosts: localhost
    connection: local
    gather_facts: False
    tags: provisioning

    # Necessary Variables for creating/provisioning the EC2 Instance
    vars_files:
      - vars/0000_vars.yml

    roles:
      - setup_ec2_vpc



