---
- hosts: "tag_Name_{{ tag_name | regex_replace(' ','_') }}"
  vars_files:
    - vars/0000_vars.yml
    - vars/vars_for_base_provision.yml
    - vars/vars_for_geerling.security.yml
  remote_user: admin
  tasks:
    - name: update the server
      become: yes
      apt: update_cache=yes

# https://github.com/ansible/ansible-modules-core/issues/3523
# have to install aptitude because apt upgrade fails (as of Dec 2016)
# fix thanks http://blog.swwomm.com/2016/04/xenial-ansible.html
    - name: install apt requirements
      become: yes
      apt: pkg=aptitude

    - name: upgrade the server
      become: yes
      apt: upgrade=full

    - name: restart machine, required after upgrade
      shell: sleep 5 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
      become: true

    - name: Wait for SSH to come up
      local_action: 
        module: wait_for
          host={{ inventory_hostname }}
          port=22
          delay=15
          timeout=100
          state=started
      become: false
