---
# tasks file for install_ansible
- name: Install packages required for Ansible
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python
    - python-dev
    - python-pip

- name: Install Ansible
  pip:
    name: ansible
